[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "boto3>=1.42.23",
    "fastapi>=0.128.0",
    "mangum>=0.20.0",
    "openai>=2.14.0",
    "pypdf>=6.5.0",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.20",
    "uvicorn>=0.39.0",
]
